### PR TITLE
Tjmadonna/1034 metadata link to home page

### PR DESCRIPTION
**Pull request by tjmadonna**
Addresses issue #1034. Requires [Search-UI PR](https://github.com/dbmi-pitt/search-ui/pull/72)

Changes
- Changed C57BL/6J-Kit<W-39J> mouse strain to C57BL/6
- Removed protein dataset from the metadata discover
- Added `uiInterval` value for volume_value facet in metadata config
- Added entities, files, and metadata button to navigation bar

### CODE REVIEW

**Review by maxsibilla — CHANGES_REQUESTED** [review]
@tjmadonna Remove the link for `Files` in the search drop down for now. We don't want to publicly support that yet. 

Also since we removed an item from the discover page please add a link for Datasets where `assay_category` is `Sequence`

**Comment by tjmadonna** [comment]
@maxsibilla Those issues have been addressed

**Comment by tjmadonna** [comment]
@maxsibilla I removed the navigation bar item and added a dropdown for navigating to metadata search

**Comment by tjmadonna** [comment]
@maxsibilla Issues are now fixed

**Pull request merged**
