### PR TITLE
Libpitt/prov 10

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. DRY repeats of components in Metadata and add key props to resolve errors
2. Apply trigger logic upon node and metadata tab btn clicks

### CODE REVIEW

**Comment by maxsibilla** [comment]
@libpitt It looks like when I click on the button under `Metadata` the Provenance UI updates but not vice-versa

**Comment by libpitt** [comment]
> @libpitt It looks like when I click on the button under `Metadata` the Provenance UI updates but not vice-versa
May need to update provenance-ui locally if not done already.

**Comment by maxsibilla** [comment]
@libpitt Updating that library fixed it. One thing though: are you able to highlight the node when the `metadata` button is clicked? Currently it looks like this which can be a little confusing
image

**Comment by libpitt** [comment]
> @libpitt Updating that library fixed it. One thing though: are you able to highlight the node when the `metadata` button is clicked? Currently it looks like this which can be a little confusing image

@maxsibilla  Updated

**Review by maxsibilla — APPROVED** [review]

**Pull request merged**
