### PR TITLE
Libpitt/tsv export #604

### PR DESCRIPTION
**Pull request by libpitt**
Change log:
1. Add checkbox functionality as `BulkExport`
a. Add checkboxes as first column to `TableResults` on search view only (not modal)
b. Add ability to export to either JSON or TSV
c. Add counter based on user selection

### CODE REVIEW

**Comment by maxsibilla** [comment]
@libpitt The checkbox to select all seems to disappear whenever a facet is selected
image

**Comment by maxsibilla** [comment]
@libpitt When a user clicks the checkbox to select all can you make it so all the entities in the results table are selected instead of just the visible ones like this:
https://jsfiddle.net/annoyingmouse/yxLrLr8o/

**Comment by libpitt** [comment]
> @libpitt When a user clicks the checkbox to select all can you make it so all the entities in the results table are selected instead of just the visible ones like this: https://jsfiddle.net/annoyingmouse/yxLrLr8o/

@maxsibilla Are we sure we want to do this? Sounds like invalid UI behavior. Gmail, Yahoo etc select what's on the page.

**Comment by libpitt** [comment]
> @libpitt The checkbox to select all seems to disappear whenever a facet is selected image

@maxsibilla This is because a new search is made after every facet selection. I can store the selected ids in the table then reselect them on useEffect.

**Comment by maxsibilla** [comment]
> > @libpitt The checkbox to select all seems to disappear whenever a facet is selected image
> 
> @maxsibilla This is because a new search is made after every facet selection. I can store the selected ids in the table then reselect them on useEffect.

I think if a user selects additional facets or enters a search query we can reset the selected entities. We always just want to show that select all checkbox though

**Comment by libpitt** [comment]
> > > @libpitt The checkbox to select all seems to disappear whenever a facet is selected image
> > 
> > 
> > @maxsibilla This is because a new search is made after every facet selection. I can store the selected ids in the table then reselect them on useEffect.
> 
> I think if a user selects additional facets or enters a search query we can reset the selected entities. We always just want to show that select all checkbox though

Oh gotcha. Noted!

**Pull request merged**
