### PR TITLE
Libpitt/editcontext

### PR DESCRIPTION
**Pull request by libpitt**
@maxsibilla The consolidation of the code to use React's Context API is complete for these pages/edit. Not sure if you want to pull in your changes on those pages into `dev-integrate` first or these ones first. Doesn't matter to me. I don't mind going through the conflicts. 

cc @yuanzhou

### CODE REVIEW

**Comment by maxsibilla** [comment]
You will need to double check the context/logic for the edit pages. I can visit http://localhost:3000/edit/dataset?uuid=create while not logged in

**Comment by maxsibilla** [comment]
@libpitt In incognito I can still access the create pages and now I just get a loading screen when trying to access the edit form of an existing  item (http://localhost:3000/edit/sample?uuid=4614ea24338ec820569f988196a5c503). This is all while I am not logged in

**Comment by libpitt** [comment]
> @libpitt In incognito I can still access the create pages and now I just get a loading screen when trying to access the edit form of an existing item (http://localhost:3000/edit/sample?uuid=4614ea24338ec820569f988196a5c503). This is all while I am not logged in

Thanks Max. I don't get a loading while not logged in. The critical access issue logic fixed though.

**Comment by maxsibilla** [comment]
@libpitt Can you resolve the conflicts in the edit pages, it may be partially just overwriting some changes as you are implementing the AppContext functionality

**Comment by libpitt** [comment]
> @libpitt Can you resolve the conflicts in the edit pages, it may be partially just overwriting some changes as you are implementing the AppContext functionality

@maxsibilla No problem. I'm working on this now. In the meantime, please can you hold off from new PR to dev-integrate which has changes to the `pages/edit`? The Context API logic I have just implemented in `pages/edit` is completely different from what was there before. 

Thanks!

**Pull request merged**
